version: '3.1'
services:
  build:
    build:
      context: ./containers/build
    volumes:
      - ./resources:/work/resources
      - ./public:/work/public
    working_dir: /work
  validate:
    build:
      context: ./containers/validate
    volumes:
      - ./public:/work/public
    working_dir: /work
  crawl:
    build:
      context: ./containers/crawl
    volumes:
      - ./resources:/work/resources
    working_dir: /work
